version: '3.8'

services:
  app:
    environment:
      - APP_DEBUG=true
      - APP_ENV=local
    volumes:
      - ./storage/logs:/var/www/html/storage/logs
      - ./storage/framework:/var/www/html/storage/framework

  frontend:
    environment:
      - NODE_ENV=development
    volumes:
      - ./node_modules:/app/node_modules

  db:
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
