# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-list-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:cached
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:cached
      - .env.docker:/var/www/html/.env
    networks:
      - todo-list
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php", "artisan", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: node:20-alpine
    container_name: todo-list-frontend
    restart: unless-stopped
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - todo-list
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: todo-list-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: todo_password
      MYSQL_USER: todo_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - todo-list
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: todo-list-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - todo-list
    depends_on:
      - db

networks:
  todo-list:
    driver: bridge
    name: todo-list-network

volumes:
  db_data:
    name: todo-list-db-data
